### ISSUE TITLE
Can't get scss-formatter to run

### ISSUE THREAD

**Issue by danieljamesross** [rl-king/scss-format#16]
Hi there, having trouble getting this package to work in Emacs 28.

I have install haskell-tools and have the following in my config:

```lisp
(use-package reformatter
       :ensure t)
(when (require 'reformatter nil 'noerror)
	(reformatter-define scss-format
	  :program "scss-format"
	  :args '("--stdin")
	  :lighter " SCSSF")
	(add-hook 'scss-mode-hook 'scss-format-on-save-mode))
```

When I call `scss-format` in `scss-mode` no formatting occurs, nor on save. Instead I get the following error:

`Error: (file-missing "Searching for program" "No such file or directory" "scss-format")`

Any help greatly appreciated, cheers.

**Comment by rl-king** [comment]
With that error it seems like emacs can't find the scss-format binary. I've been using it with doom-emacs which does some things to get everything on your PATH to be available to emacs. The last bullet [here](https://github.com/hlissner/doom-emacs#features).

I've used spacemacs before and ran in to issues with similar stuff, depending on [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) resolved those issues. 

I'm sure there is a way to do this without a dependency, I don't know much about emacs config besides the doom-emacs stuff.

**Comment by danieljamesross** [comment]
Hey, thanks for replying!

This makes sense. I'll implement a fix, thanks very much.
